{
 "title": "miner stats",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "validator penalty",
   "type": "graph",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "validator_ledger{subtype!=\"total\"}\n"
    },
    { "expr": "validator_inconsensus  " }
   ]
  },
  {
   "title": "validator version",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "validator_version_info" }
   ]
  },
  {
   "title": "validator sessions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "validator_sessions" }
   ]
  },
  {
   "title": "block age",
   "type": "graph",
   "gridPos": { "h": 6, "w": 17, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "validator_block_age" }
   ]
  },
  {
   "title": "connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 17, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "validator_connections" }
   ]
  }
 ]
}